#!/bin/bash
# This is a simple script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the build step.  This script gets executed directly, so it
# could be python, php, ruby, etc.
mvn install:install-file -Dfile=../../pablow/repo/gdata-client-1.0.jar -DgroupId=com.google -DartifactId=gdata-client -Dversion=1.0 -Dpackaging=jar
mvn install:install-file -Dfile=../../pablow/repo/gdata-core-1.0.jar -DgroupId=com.google -DartifactId=gdata-core -Dversion=1.0 -Dpackaging=jar
mvn install:install-file -Dfile=../../pablow/repo/gdata-maps-2.0.jar -DgroupId=com.google -DartifactId=gdata-maps -Dversion=2.0 -Dpackaging=jar
mvn install:install-file -Dfile=../../pablow/repo/gdata-media-1.0.jar -DgroupId=com.google -DartifactId=gdata-media -Dversion=1.0 -Dpackaging=jar
mvn install:install-file -Dfile=../../pablow/repo/gdata-youtube-2.0.jar -DgroupId=com.google -DartifactId=gdata-youtube -Dversion=2.0 -Dpackaging=jar
mvn install:install-file -Dfile=../../pablow/repo/google-collect-1.0.jar -DgroupId=com.google -DartifactId=google-collect -Dversion=1.0 -Dpackaging=jar
mvn install:install-file -Dfile=../../pablow/repo/mail.jar -DgroupId=com.google -DartifactId=google-mail -Dversion=1.0 -Dpackaging=jar